### ISSUE TITLE
Importing distro on windows/mac results in unexpected behavior

### ISSUE THREAD

**Issue by nir0s** [nir0s/distro#124]
Trying to import distro on Windows/Mac results in some weird behavior. For instance, on Windows, it tries to execute `lsb_release -a` and exists on a ProcessError.

I suggest we test that:

```python
if not sys.platform.startswith('linux'):
    raise ImportError('distro currently only supports Linux')
```

That way, users can do:

```python
try:
    import distro
except ImportError:
    pass
```

which seems reasonable to me.

Thoughts?

**Comment by MartijnBraam** [comment]
I think it might be beter to return a generic "Unsupported distribution / operating system" distro name when the distro cannot be detected.

I assume this is also a problem on linux distributions without any release information files.

**Comment by nir0s** [comment]
Linux distros with no info return empty strings.

**Comment by MartijnBraam** [comment]
I think that raising an ImportError is not the right error and not the right place to raise an exception for this. 

It is a little hard to change that since the linux distro is detected as soon as the module is imported. Maybe also return empty strings for osx and windows and have a `distro.is_linux` property. 

Another option is simply having the id `windows`, `osx` and `genericlinux` for when no information is available

**Comment by nir0s** [comment]
I like the empty strings with the distro.is_linux property suggestion.

**Comment by nir0s** [comment]
I tried implementing this.. and it seems to create more confusing and overhead than just raising an ImportError exception. `sh` does the same thing (https://github.com/amoffat/sh/blob/master/sh.py#L34)

I believe we should go with this.

**Comment by nir0s** [comment]
PR open. Let's keep discussing.
